### ISSUE TITLE
Crash with 0.17.64

### ISSUE THREAD

**Issue by PSquared1234** [osldgoth/Actual-Craft-Time#9]
I'm experiencing a problem that causes Factorio to crash when using your mod. I can't say when this error first started happening, but it's within the last few days (more specifically, I just noticed it tonight, but I cannot say whether or not I've used your mod within the last 2 days or so). Certainly since 17.63 was released. I'm using version 0.3.9 of your mod.

When I click on an assembler and focus on your mod, initially it works. But if I try to increase the number of assemblers, I get the following error: [(link)](https://steamuserimages-a.akamaihd.net/ugc/773976809192982533/E71CD576D83A2C1AD2C1539EA70D5A1BD89B7FB5/). The error is repeatable, and seems to occur regardless of the product being made in the assembler. Savefile available if you need it.

FYI, and thanks for a great mod. I hope this is an easy fix.

**Comment by OvermindDL1** [comment]
Still happening in Factorio 0.17.69 Release (non-experimental) version.

As per https://mods.factorio.com/mod/Actual_Craft_Time/discussion/5d4e71385ea028000d5562cc it seems the fix is fairly simple, on line 657:

```patch
- local sliderLabelCaption = tostring(playersGui["ACT-frame_"..event.player_index]["machineFlow"]["sliderFlow"]["sliderLabel"].caption)
+ local sliderLabelCaption = playersGui["ACT-frame_"..event.player_index]["machineFlow"]["sliderFlow"]["sliderLabel"].caption[3]
```

Not personally tested but the thread is full of people that say it works for them.  The issue is caused by:

> This is due to 17.64 changes. Specifically:
> - Removed the ability to convert a table address into a string logging sliderLabelCaption returns "table", so when trying to sub anything from it as a string, nothing happens and the crash happens because you're trying to find a substring in something that isn't a string

**Comment by OvermindDL1** [comment]
For note @osldgoth, if you don't have time to keep the mod up-to-date then if you [add me as a mod collaborator on the mod portal](https://mods.factorio.com/mod/Actual_Craft_Time/permissions) (`OvermindDL1`) as well as push access here then I can perform the necessary updates and bug fixes if any such issues occur.
